Add delay on server
Aquantia/iperf pull request #20
Opened 2019-07-18 14:04 UTC by WerWebWer

A new feature has been added. It allows you to create a delay on the server in milliseconds. You can use "--delay <unsigned int>"

2019-07-18 14:26 UTC, cail commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2019-07-18 14:30 UTC, WerWebWer commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
I deleted this file

2019-07-18 14:32 UTC, cail requested changes
general: revert spacing changes, see other comments as well.

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> +    if (test->delay > 0 ) iperf_printf(test, " with max delay = %i\n", test->delay);
fix code style, each statement on separate line.

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> -		    if (test->protocol->id == Ptcp) {
Why spacing only changes? revert these

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> +			            cleanup_server(test);
revert spacing changes

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> -		    }
revert spacing changes

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> -                             * If the protocol isn't UDP, or even if it is but
revert spacing changes

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> +            iperf_printf(test, "Delay start -> ");
There will be a huge printout flood. Remove printf at all.

2019-07-18 14:32 UTC, cail commented on src/iperf_server_api.c
> +            usleep(i*1000);
How do you guarantee this delay will happen once every second?

2019-07-18 14:56 UTC, WerWebWer commented
I reverted spacing changes. And delay will appear when the result is 0, and t depends on time

2019-07-19 08:46 UTC, cail commented on src/iperf_server_api.c
> +	if (test->delay > 0 ) iperf_printf(test, "Server listening on %d  with max delay = %i\n", test->server_port, test->delay);
Separate `if` and statement on different lines: that a generic coding rule:

```
if (test->delay > 0 )
    iperf_printf(....)
else
    iperf_printf()
```

2019-07-19 09:50 UTC, WerWebWer commented
With corrected if

2019-09-03 15:08 UTC, cail commented
@WerWebWer plz fix the outstanding comments so we can merge in.

2019-10-13 08:01 UTC, merged