Bidirectional
Aquantia/iperf pull request #8
Opened 2018-08-03 08:48 UTC by LikHait

Add --bidirectional option

2018-08-03 09:49 UTC, cail requested changes

2018-08-03 09:49 UTC, cail commented on src/iperf_api.c
> +        ipt->mode = ! ipt->mode;
thats enum here, can't use `!`

2018-08-03 09:49 UTC, cail commented on src/iperf_api.c
> +        ipt->mode = ! ipt->mode;
same

2018-08-03 09:49 UTC, cail commented on src/iperf_api.c
> +        {"bidirectional", no_argument, NULL, OPT_BIDIRECTIONAL},
`--bidir` is way better?

2018-08-03 10:44 UTC, LikHait commented
* Implemented --bidir (bidirectional) option for iperf.
* iperf_test: int sender is replaced with enum test_mode mode with SENDER, RECEIVER and BIDIRECTIONAL states.
* iperf_stream: add new variable "sender"
* Now streams are created depending on mode:
	sender == 1 if test-> mode == SENDER
	sender == 0 if test-> mode == RECEIVER
	sender == 1 && sender == 0 if test-> mode == BIDIRECTIONAL
* iperf_new_stream (struct iperf_test * test, int s) => iperf_new_stream (struct iperf_test * test, int s, int part)
* Summary information is output for each type of iperf_stream (sender and receiver)

2018-08-06 13:57 UTC, cail approved these changes

2018-08-10 08:17 UTC, merged